name: "Quix Samples readme.md importer"
description: "Import readmes from the Quix Samples into mkdocs"
author: "Steve Rosam"
branding:
  icon: 'book'
  color: 'blue'
inputs:
  LIBRARY_REPO_PATH:
    description: "Path to the repo"
    default: "samples"
    required: true
  DOCS_PATH:
    description: "Path to docs"
    default: "docs"
    required: true
  REPLACEMENT_PLACEHOLDER:
    description: "MKDocs menu placeholder to be replaced"
    default: ""
    required: true
  CONNECTORS_TITLE_REPLACEMENT:
    description: "Replace connectors title"
    default: ""
    required: false
  CONNECTORS_TAG:
    description: "The tag to use to locale connectors in the library"
    default: ""
    required: true
  NAV_INDENT_SPACES:
    description: "Indent the nave by this number of spaces"
    default: "6"
    required: true
outputs:
  logs:
    description: "Log output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
